### ISSUE TITLE
How to get well formatted spec errors.

### ISSUE THREAD

**Issue by drewverlee** [oakes/odoyle-rum#6]
When i get a spec error it shows as munged in the chrome dev console. I can get more information if it helps, i'm curious how to improve the readability of these errors. This might not be a odoyle-rum specific question, but i thought i would start my search here.

**Comment by oakes** [comment]
Looks OK to me?
<img width="455" alt="Screen Shot 2022-05-31 at 10 40 07 PM" src="https://user-images.githubusercontent.com/216147/171280747-0e4be3bc-6295-4c90-9873-3d69e81b17e0.png">

**Comment by drewverlee** [comment]
It does look good. It seems I was looking somewhere else, as it does show fine in chrome. Maybe I had firefox open for a bit? Figwheel also munges the error a bit. But as long as it looks good in chrome i don't see anything that needs doing. 

Closing this.
